spring.datasource.url=jdbc:mysql://localhost:3306/a3_store
spring.datasource.username=root
spring.datasource.password=sql123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080

# Google OAuth
google.clientId=248293899743-8f23fa59nff7ur1ghufnkgiti8vnae82.apps.googleusercontent.com
